workflows:
  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
