workflows:
  ios-workflow:
    name: iOS Debug Build
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get packages
        script: |
          cd frontend
          flutter pub get
      - name: Build iOS
        script: |
          cd frontend
          flutter build ios --debug --no-codesign
    artifacts:
      - frontend/build/ios/iphoneos/Runner.app
